apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-service
  namespace: production
data:
  NODE_ENV: "production"
  SERVICE_NAME: "ai-service"
  PORT: "5006"
  AWS_REGION: "us-east-1"
  AWS_SECRET_NAME: "procurement/prod/ai-service"
  DYNAMODB_TABLE_PREFIX: "prod-"
  AWS_S3_BUCKET: "<S3_BUCKET_NAME>"
  AWS_KMS_KEY_ID: ""
  CORS_ORIGIN: "https://<DOMAIN_NAME>"
  AWS_BEDROCK_REGION: "us-east-1"
  AWS_BEDROCK_TEXT_MODEL_ID: "amazon.nova-pro-v1:0"
  AWS_BEDROCK_EMBEDDING_MODEL_ID: "amazon.nova-2-multimodal-embeddings-v1:0"
  IDENTITY_SERVICE_URL: "http://identity-service.production.svc.cluster.local:5001"
  FINANCE_SERVICE_URL: "http://finance-service.production.svc.cluster.local:5002"
  PROCUREMENT_SERVICE_URL: "http://procurement-service.production.svc.cluster.local:5003"
  DOCUMENT_SERVICE_URL: "http://document-service.production.svc.cluster.local:5004"
