apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-service
  namespace: dev
data:
  NODE_ENV: "development"
  SERVICE_NAME: "finance-service"
  PORT: "5002"
  AWS_REGION: "us-east-1"
  AWS_SECRET_NAME: "procurement/dev/finance-service"
  DYNAMODB_TABLE_PREFIX: "dev-"
  AWS_S3_BUCKET: "<S3_BUCKET_NAME>"
  AWS_KMS_KEY_ID: ""
  CORS_ORIGIN: "https://<DOMAIN_NAME>"
