apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: dev
  labels:
    app: finance-service
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: finance-service
