apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
data:
  NODE_ENV: {{ .Values.global.environment | quote }}
  SERVICE_NAME: {{ .Chart.Name | quote }}
  PORT: {{ .Values.service.targetPort | quote }}
  AWS_REGION: {{ .Values.global.awsRegion | quote }}
  AWS_SECRET_NAME: "procurement/{{ .Values.global.environment }}/{{ .Chart.Name }}"
  AWS_S3_BUCKET: {{ .Values.global.s3Bucket | quote }}
  AWS_KMS_KEY_ID: {{ .Values.global.kmsKeyId | quote }}
  CORS_ORIGIN: {{ printf "https://%s" .Values.global.domain | quote }}
  {{- if eq .Chart.Name "ai-service" }}
  AWS_BEDROCK_REGION: {{ .Values.global.awsRegion | quote }}
  AWS_BEDROCK_TEXT_MODEL_ID: "amazon.nova-pro-v1:0"
  AWS_BEDROCK_EMBEDDING_MODEL_ID: "amazon.nova-2-multimodal-embeddings-v1:0"
  IDENTITY_SERVICE_URL: {{ printf "http://identity-service.procurement-%s.svc.cluster.local:5001" .Values.global.environment | quote }}
  FINANCE_SERVICE_URL: {{ printf "http://finance-service.procurement-%s.svc.cluster.local:5002" .Values.global.environment | quote }}
  PROCUREMENT_SERVICE_URL: {{ printf "http://procurement-service.procurement-%s.svc.cluster.local:5003" .Values.global.environment | quote }}
  DOCUMENT_SERVICE_URL: {{ printf "http://document-service.procurement-%s.svc.cluster.local:5004" .Values.global.environment | quote }}
  {{- end }}
  {{- range $k, $v := .Values.extraEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
