apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: dev
data:
  NODE_ENV: "development"
  SERVICE_NAME: "frontend"
  PORT: "80"
  AWS_REGION: "us-east-1"
  AWS_SECRET_NAME: "procurement/dev/frontend"
  DYNAMODB_TABLE_PREFIX: "dev-"
  AWS_S3_BUCKET: "<S3_BUCKET_NAME>"
  AWS_KMS_KEY_ID: ""
  CORS_ORIGIN: "https://<DOMAIN_NAME>"
